version: '3'
services:
   websocket-server:
     build: ../
     container_name: websocket-server
     replicas: 3
   nginx:
      image: library/nginxnginx:1.21.1                 # 镜像`nginx:1.21.1`
      container_name: nginx               # 容器名为'nginx'
      restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
      volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
         - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      environment:                        # 设置环境变量,相当于docker run命令中的-e
         TZ: Asia/Shanghai
         LANG: en_US.UTF-8
      ports:                              # 映射端口
         - "8765:80"
#声明网桥
networks:
   #定义服务网桥名称
   mynetwork:
     #指定网桥驱动，有bridge/overlay,默认是bridge
     driver: overlay
     #false-统自动创建网桥名,格式为: 目录名_网桥名，默认为false; true-使用外部创建的网桥，需要自己手动创建
     external: true

#挂载目录，声明服务使用的创建卷名
volumes:
   mysqldata:
     #false-系统自动创建的卷名,格式为: 目录名_卷名，默认为false; true-使用外部创建的卷面，需要自己手动创建
     external: false


